"""empty message

Revision ID: 7fbb97658c07
Revises: 
Create Date: 2022-06-02 19:11:12.848245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbb97658c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=120), nullable=False),
    sa.Column('rent_fee', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport')
    # ### end Alembic commands ###
