"""empty message

Revision ID: b839718f3ed8
Revises: 7fbb97658c07
Create Date: 2022-06-02 20:52:18.975920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b839718f3ed8'
down_revision = '7fbb97658c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
